const SUPABASE_URL = "https://qcqqmbpvcdpmdsohjhsc.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjcXFtYnB2Y2RwbWRzb2hqaHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNjEzMDIsImV4cCI6MjA4NDczNzMwMn0.P301ZKDqIefx9d1PhOGMknE28ao1BmfFYN0INyeGWbg";
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);